# Generated by Django 5.2.7 on 2025-10-02 05:55

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('platform', models.CharField(choices=[('general', 'General'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('twitter', 'Twitter'), ('website', 'Website'), ('email', 'Email')], default='general', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('max_length', models.IntegerField(default=1000, help_text='Maximum character length')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['platform', 'name'],
                'unique_together': {('name', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='GenerationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.CharField(blank=True, max_length=100)),
                ('product_features', models.TextField(blank=True)),
                ('target_audience', models.CharField(blank=True, max_length=200)),
                ('brand_story', models.TextField(blank=True)),
                ('unique_selling_point', models.TextField(blank=True)),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual'), ('luxury', 'Luxury'), ('friendly', 'Friendly'), ('energetic', 'Energetic'), ('minimalist', 'Minimalist'), ('traditional', 'Traditional'), ('modern', 'Modern')], default='professional', max_length=20)),
                ('length', models.CharField(choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long')], default='medium', max_length=10)),
                ('variations_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('model_type', models.CharField(default='fast', max_length=20)),
                ('max_tokens', models.IntegerField(default=1000)),
                ('original_prompt', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('generated_tokens', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.productcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('template_prompt', models.TextField(help_text='Template with placeholders like {product_name}')),
                ('example_output', models.TextField(blank=True)),
                ('default_tone', models.CharField(default='professional', max_length=20)),
                ('default_length', models.CharField(default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.contenttype')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.productcategory')),
            ],
            options={
                'ordering': ['-is_featured', '-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_requests', models.IntegerField(default=0)),
                ('successful_generations', models.IntegerField(default=0)),
                ('failed_generations', models.IntegerField(default=0)),
                ('total_content_pieces', models.IntegerField(default=0)),
                ('favorite_content_count', models.IntegerField(default=0)),
                ('published_content_count', models.IntegerField(default=0)),
                ('fast_model_usage', models.IntegerField(default=0)),
                ('quality_model_usage', models.IntegerField(default=0)),
                ('total_estimated_cost', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('first_usage', models.DateTimeField(blank=True, null=True)),
                ('last_usage', models.DateTimeField(blank=True, null=True)),
                ('monthly_request_limit', models.IntegerField(default=100)),
                ('monthly_requests_used', models.IntegerField(default=0)),
                ('current_month', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Usage Stats',
                'verbose_name_plural': 'User Usage Stats',
            },
        ),
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_text', models.TextField()),
                ('edited_text', models.TextField(blank=True, help_text='User-edited version')),
                ('final_text', models.TextField(blank=True, help_text='Final approved version')),
                ('model_id', models.CharField(max_length=100)),
                ('variation_number', models.IntegerField(default=1)),
                ('was_cached', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('quality_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], help_text='User rating of content quality', null=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('copy_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_content', to='generator.generationrequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='generator_g_user_id_101706_idx'), models.Index(fields=['is_favorite', '-created_at'], name='generator_g_is_favo_10f9bf_idx'), models.Index(fields=['request', 'variation_number'], name='generator_g_request_25ba48_idx')],
            },
        ),
    ]
