# Generated by Django 5.2.7 on 2025-10-04 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userusagestats',
            name='current_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userusagestats',
            name='daily_request_limit',
            field=models.IntegerField(default=20, help_text='Maximum requests per day'),
        ),
        migrations.AddField(
            model_name='userusagestats',
            name='daily_requests_used',
            field=models.IntegerField(default=0),
        ),
    ]
