# Generated by Django 5.2.7 on 2025-10-04 11:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_userusagestats_current_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userusagestats',
            name='current_date',
        ),
        migrations.AddField(
            model_name='userusagestats',
            name='last_daily_reset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userusagestats',
            name='current_month',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userusagestats',
            name='daily_request_limit',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='userusagestats',
            name='monthly_request_limit',
            field=models.IntegerField(default=1000),
        ),
    ]
