# Generated by Django 5.2.7 on 2025-10-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_remove_userusagestats_current_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userusagestats',
            name='daily_request_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='userusagestats',
            name='monthly_request_limit',
            field=models.IntegerField(default=200),
        ),
    ]
