version: '3.8'

services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"  # Only bind to localhost
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_HOST=host.docker.internal
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

# No database service since we're using host MySQL

volumes:
  static_volume:
  media_volume: