version: '3.8'

services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"  # Only bind to localhost
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./staticfiles:/app/staticfiles  # Bind mount for Apache access
      - media_volume:/app/media

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"  # Only bind to localhost

volumes:
  postgres_data:
  media_volume: